repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [--settings-path=pyproject.toml]
        exclude: (migrations|venv)

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        args: [--config=pyproject.toml]

  - repo: https://gitlab.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies: [flake8-docstrings, flake8-import-order]
        args: [--config=.flake8]
        exclude: (migrations|venv)

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.4.1
    hooks:
      - id: mypy
        args: [--config-file=mypy.ini]
        exclude: (migrations|venv)

  - repo: https://github.com/PyCQA/pylint
    rev: 2.17.5
    hooks:
      - id: pylint
        args: [--rcfile=.pylintrc]
        exclude: (migrations|venv)