repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: python
        types: [python]
        args: [--config=pyproject.toml]

      - id: isort
        name: isort
        entry: isort
        language: python
        types: [python]
        args: [--settings-path=pyproject.toml]

      - id: flake8
        name: flake8
        entry: flake8
        language: python
        types: [python]
        args: [--config=.flake8]

      - id: mypy
        name: mypy
        entry: mypy
        language: python
        types: [python]
        args: [--config=mypy.ini]

      - id: pylint
        name: pylint
        entry: pylint
        language: python
        types: [python]
        args: [--rcfile=.pylintrc]